name=input("ra gqvia: ")
surname=input("sheni gvari: ")
age=input("ramdeni wlis xar: ")
fav_food=input("sayvareli skvebi: ")
birth_year=input("dabadebis weli: ")
pc=input("komp gaq: ")
phone=input("telefoni gaq: ")
print(name + " " + surname ,"misi asaki" , str(age), " " , "sayvareli saymeli" , fav_food , str(birth_year) ,"kompiuteri aqvs tu ara" , pc ," tele aqvs tu ara "+ phone)